version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: Demo.Web/Dockerfile
        image: demo.web
        env_file: 
            - Demo.Web/web.env
        volumes:
            - ./Logs/Web:/app/Logs/
        ports:
            - "8000:80"
        depends_on:
            - db
        entrypoint: ["dotnet", "Demo.Web.dll"]
    db:
        build: 
            context: .
            dockerfile: Demo.Db/Dockerfile
        image: "demo.sqlserver"
        env_file: 
            - Demo.Db/db.env
        expose:
            - "1432"
        ports: 
            - "1432:1433"
volumes:
    demoweb-data:
     